package runtime

import (
	"bytes"
	"encoding/json"
	"errors"
	"sort"
	"strings"
)

// MongoDB treats the first BSON key as the command. Maps generated by forms
// otherwise sort "filter" before "find" and become invalid wire commands.
func mongoCommand(text string) (string, error) {
	if !strings.HasPrefix(strings.TrimSpace(text), "{") {
		return text, nil
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal([]byte(text), &fields); err != nil {
		return "", err
	}
	known := strings.Fields("find count aggregate distinct listCollections listIndexes collStats dbStats serverStatus ping buildInfo hello isMaster explain insert update delete findAndModify create drop createIndexes dropIndexes renameCollection dropDatabase")
	command := ""
	for _, key := range known {
		if _, ok := fields[key]; !ok {
			continue
		}
		if command != "" {
			return "", errors.New("MongoDB input contains multiple commands")
		}
		command = key
	}
	if command == "" {
		return text, nil
	}
	if command == "find" {
		var limit int64
		_ = json.Unmarshal(fields["limit"], &limit)
		if limit <= 0 || limit > MaxRows+1 {
			fields["limit"] = json.RawMessage("10001")
		}
	}
	keys := make([]string, 0, len(fields))
	for key := range fields {
		if key != command {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	keys = append([]string{command}, keys...)
	var result bytes.Buffer
	result.WriteByte('{')
	for i, key := range keys {
		if i > 0 {
			result.WriteByte(',')
		}
		encoded, _ := json.Marshal(key)
		result.Write(encoded)
		result.WriteByte(':')
		result.Write(fields[key])
	}
	result.WriteByte('}')
	return result.String(), nil
}
